workflows:
  build-release:
    name: Yalla Passenger iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Yalla Passenger
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yalla.yallaPassenger
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up dependencies
        script: |
          flutter packages pub get
      - name: Set up Code Signing
        script: |
          xcode-project use-profiles
      - name: Build Flutter IPA
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild.log
